download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/crowdstrike-falcon-4.6.0.tar.gz
format_version: 1.0.0
name: falcon
namespace: crowdstrike
server: https://galaxy.ansible.com/api/
signatures: []
version: 4.6.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/crowdstrike/falcon/versions/4.6.0/
