- hosts: 10.8.109.236
  #ignore_errors: true
  roles:
    - role: crowdstrike.falcon.falcon_install
      vars:
        falcon_client_id: 
        falcon_client_secret: 
        falcon_sensor_version_decrement: 2

    - role: crowdstrike.falcon.falcon_configure
      vars:
        falcon_client_id: 
        falcon_client_secret: 
        falcon_tags: 'falcon,example,tags'

