- hosts: windows
  #ignore_errors: true
  roles:
    - role: crowdstrike.falcon.falcon_install
      vars:
        falcon_client_id: <FALCON_CLIENT_ID>
        falcon_client_secret: <FALCON_CLIENT_SECRET>
        falcon_sensor_version_decrement: 2

